spring.application.name=gcp-spring-boot-template
server.port=${PORT:8080}

# Cloud SQL Configuration
spring.cloud.gcp.sql.database-name=${CLOUD_SQL_DATABASE_NAME:sample_db}
spring.cloud.gcp.sql.instance-connection-name=${CLOUD_SQL_CONNECTION_NAME:proven-country-479800-f7:europe-west2:sample-db-instance}

# Database Credentials
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:password123}

# Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQL Script initialization
spring.sql.init.mode=always
