-- Search configuration table
CREATE TABLE IF NOT EXISTS search_config (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    origin_airport VARCHAR(10) NOT NULL,
    destination_airport VARCHAR(10) NOT NULL,
    search_from_date DATE,
    search_to_date DATE,
    min_price INTEGER,
    max_price INTEGER,
    trip_type VARCHAR(20) NOT NULL DEFAULT 'BOTH',
    poll_interval_minutes INTEGER NOT NULL DEFAULT 360,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_scraped_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Flight results table
CREATE TABLE IF NOT EXISTS flight_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT REFERENCES search_config(id),
    price INTEGER,
    currency VARCHAR(10) DEFAULT 'SEK',
    departure_date DATE,
    return_date DATE,
    departure_time VARCHAR(10),
    arrival_time VARCHAR(10),
    return_departure_time VARCHAR(10),
    return_arrival_time VARCHAR(10),
    airline VARCHAR(255),
    trip_type VARCHAR(20),
    booking_url TEXT,
    checksum VARCHAR(64) NOT NULL,
    scraped_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_flight_checksum UNIQUE (checksum)
);

-- Scrape execution log
CREATE TABLE IF NOT EXISTS scrape_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    config_id BIGINT REFERENCES search_config(id),
    status VARCHAR(20) NOT NULL,
    flights_found INTEGER DEFAULT 0,
    new_flights_saved INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    finished_at TIMESTAMP WITH TIME ZONE
);

-- Default config: ARN to IOA, both trip types, 2 months window
INSERT INTO search_config (name, origin_airport, destination_airport, search_from_date, search_to_date, trip_type, poll_interval_minutes)
VALUES ('ARN to IOA - Default', 'ARN', 'IOA', CURRENT_DATE, DATEADD('MONTH', 2, CURRENT_DATE), 'BOTH', 360);
